<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class Any implements \JsonSerializable
{
    public function __construct(
        public ?string $atType = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $atType = null;
        if (array_key_exists('@type', $data)) {
            $atType = $data['@type'];
            if ($atType === null) {
                $atType = null;
            } else {
                if (!is_string($atType)) {
                    throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . '@type'));
                }
            }
        }
        return new self(atType: $atType);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['@type' => $this->atType], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
