<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class Assertion implements \JsonSerializable
{
    public function __construct(
        public bool $expectation,
        public AssertionTupleKey $tupleKey,
        /** @var array<string, mixed>|null */
        public ?array $context = null,
        /** @var list<TupleKey>|null */
        public ?array $contextualTuples = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('expectation', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'expectation'));
        }
        if (!is_bool($data['expectation'])) {
            throw new FgaValidationException(sprintf('%s: expected bool', ($path === '' ? '' : $path . '.') . 'expectation'));
        }
        $expectation = $data['expectation'];
        if (!array_key_exists('tuple_key', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'tuple_key'));
        }
        if (!is_array($data['tuple_key'])) {
            throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'tuple_key'));
        }
        $tupleKey = AssertionTupleKey::fromArray($data['tuple_key'], ($path === '' ? '' : $path . '.') . 'tuple_key');
        $context = null;
        if (array_key_exists('context', $data)) {
            $context = $data['context'];
            if (!is_array($context)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'context'));
            }
        }
        $contextualTuples = null;
        if (array_key_exists('contextual_tuples', $data)) {
            $contextualTuples = $data['contextual_tuples'];
            if (!is_array($contextualTuples)) {
                throw new FgaValidationException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'contextual_tuples'));
            }
            $contextualTuplesList = [];
            foreach ($contextualTuples as $idx => $item) {
                if (!is_array($item)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
                }
                $contextualTuplesList[] = TupleKey::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
            }
            $contextualTuples = $contextualTuplesList;
        }
        return new self(expectation: $expectation, tupleKey: $tupleKey, context: $context, contextualTuples: $contextualTuples);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['expectation' => $this->expectation, 'tuple_key' => $this->tupleKey->toArray(), 'context' => $this->context, 'contextual_tuples' => $this->contextualTuples === null ? null : array_map(static fn(TupleKey $v): array => $v->toArray(), $this->contextualTuples)], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
