<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

enum AuthErrorCode: string
{
    case NO_AUTH_ERROR = 'no_auth_error';
    case AUTH_FAILED_INVALID_SUBJECT = 'auth_failed_invalid_subject';
    case AUTH_FAILED_INVALID_AUDIENCE = 'auth_failed_invalid_audience';
    case AUTH_FAILED_INVALID_ISSUER = 'auth_failed_invalid_issuer';
    case INVALID_CLAIMS = 'invalid_claims';
    case AUTH_FAILED_INVALID_BEARER_TOKEN = 'auth_failed_invalid_bearer_token';
    case BEARER_TOKEN_MISSING = 'bearer_token_missing';
    case UNAUTHENTICATED = 'unauthenticated';
    case FORBIDDEN = 'forbidden';
}
