<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class AuthorizationModel implements \JsonSerializable
{
    public function __construct(
        public string $id,
        public string $schemaVersion,
        /** @var list<TypeDefinition> */
        public array $typeDefinitions,
        /** @var array<string, mixed>|null */
        public ?array $conditions = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('id', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'id'));
        }
        if (!is_string($data['id'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'id'));
        }
        $id = $data['id'];
        if (!array_key_exists('schema_version', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'schema_version'));
        }
        if (!is_string($data['schema_version'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'schema_version'));
        }
        $schemaVersion = $data['schema_version'];
        if (!array_key_exists('type_definitions', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'type_definitions'));
        }
        if (!is_array($data['type_definitions'])) {
            throw new FgaValidationException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'type_definitions'));
        }
        $typeDefinitionsList = [];
        foreach ($data['type_definitions'] as $idx => $item) {
            if (!is_array($item)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
            }
            $typeDefinitionsList[] = TypeDefinition::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
        }
        $typeDefinitions = $typeDefinitionsList;
        $conditions = null;
        if (array_key_exists('conditions', $data)) {
            $conditions = $data['conditions'];
            if (!is_array($conditions)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'conditions'));
            }
        }
        return new self(id: $id, schemaVersion: $schemaVersion, typeDefinitions: $typeDefinitions, conditions: $conditions);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['id' => $this->id, 'schema_version' => $this->schemaVersion, 'type_definitions' => array_map(static fn(TypeDefinition $v): array => $v->toArray(), $this->typeDefinitions), 'conditions' => $this->conditions], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
