<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class BatchCheckResponse implements \JsonSerializable
{
    public function __construct(
        /** @var array<string, mixed>|null */
        public ?array $result = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $result = null;
        if (array_key_exists('result', $data)) {
            $result = $data['result'];
            if ($result === null) {
                $result = null;
            } else {
                if (!is_array($result)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'result'));
                }
            }
        }
        return new self(result: $result);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['result' => $this->result], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
