<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class BatchCheckSingleResult implements \JsonSerializable
{
    public function __construct(
        public ?bool $allowed = null,
        public ?CheckError $error = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $allowed = null;
        if (array_key_exists('allowed', $data)) {
            $allowed = $data['allowed'];
            if ($allowed === null) {
                $allowed = null;
            } else {
                if (!is_bool($allowed)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected bool', ($path === '' ? '' : $path . '.') . 'allowed'));
                }
            }
        }
        $error = null;
        if (array_key_exists('error', $data)) {
            $error = $data['error'];
            if ($error === null) {
                $error = null;
            } else {
                if (!is_array($error)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'error'));
                }
                $error = CheckError::fromArray($error, ($path === '' ? '' : $path . '.') . 'error');
            }
        }
        return new self(allowed: $allowed, error: $error);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['allowed' => $this->allowed, 'error' => $this->error?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
