<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class BatchCheckBody implements \JsonSerializable
{
    public function __construct(
        /** @var list<BatchCheckItem> */
        public array $checks,
        public ?string $authorizationModelId = null,
        public ?ConsistencyPreference $consistency = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('checks', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'checks'));
        }
        if (!is_array($data['checks'])) {
            throw new FgaValidationException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'checks'));
        }
        $checksList = [];
        foreach ($data['checks'] as $idx => $item) {
            if (!is_array($item)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
            }
            $checksList[] = BatchCheckItem::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
        }
        $checks = $checksList;
        $authorizationModelId = null;
        if (array_key_exists('authorization_model_id', $data)) {
            $authorizationModelId = $data['authorization_model_id'];
            if ($authorizationModelId === null) {
                $authorizationModelId = null;
            } else {
                if (!is_string($authorizationModelId)) {
                    throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'authorization_model_id'));
                }
            }
        }
        $consistency = null;
        if (array_key_exists('consistency', $data)) {
            $consistency = $data['consistency'];
            if ($consistency === null) {
                $consistency = null;
            } else {
                if (!is_string($consistency)) {
                    throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'consistency'));
                }
                try {
                    $consistency = ConsistencyPreference::from($consistency);
                } catch (\ValueError) {
                    throw new FgaValidationException(sprintf('%s: invalid enum value', ($path === '' ? '' : $path . '.') . 'consistency'));
                }
            }
        }
        return new self(checks: $checks, authorizationModelId: $authorizationModelId, consistency: $consistency);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['checks' => array_map(static fn(BatchCheckItem $v): array => $v->toArray(), $this->checks), 'authorization_model_id' => $this->authorizationModelId, 'consistency' => $this->consistency?->value], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
