<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class BatchCheckItem implements \JsonSerializable
{
    public function __construct(
        public string $correlationId,
        public CheckRequestTupleKey $tupleKey,
        /** @var array<string, mixed>|null */
        public ?array $context = null,
        public ?ContextualTupleKeys $contextualTuples = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('correlation_id', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'correlation_id'));
        }
        if (!is_string($data['correlation_id'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'correlation_id'));
        }
        $correlationId = $data['correlation_id'];
        if (!array_key_exists('tuple_key', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'tuple_key'));
        }
        if (!is_array($data['tuple_key'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'tuple_key'));
        }
        $tupleKey = CheckRequestTupleKey::fromArray($data['tuple_key'], ($path === '' ? '' : $path . '.') . 'tuple_key');
        $context = null;
        if (array_key_exists('context', $data)) {
            $context = $data['context'];
            if ($context === null) {
                $context = null;
            } else {
                if (!is_array($context)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'context'));
                }
            }
        }
        $contextualTuples = null;
        if (array_key_exists('contextual_tuples', $data)) {
            $contextualTuples = $data['contextual_tuples'];
            if ($contextualTuples === null) {
                $contextualTuples = null;
            } else {
                if (!is_array($contextualTuples)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'contextual_tuples'));
                }
                $contextualTuples = ContextualTupleKeys::fromArray($contextualTuples, ($path === '' ? '' : $path . '.') . 'contextual_tuples');
            }
        }
        return new self(correlationId: $correlationId, tupleKey: $tupleKey, context: $context, contextualTuples: $contextualTuples);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['correlation_id' => $this->correlationId, 'tuple_key' => $this->tupleKey->toArray(), 'context' => $this->context, 'contextual_tuples' => $this->contextualTuples?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
