<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class CheckError implements \JsonSerializable
{
    public function __construct(
        public ErrorCode|string|null $inputError = null,
        public InternalErrorCode|string|null $internalError = null,
        public ?string $message = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $inputError = null;
        if (array_key_exists('input_error', $data)) {
            $inputError = $data['input_error'];
            if ($inputError === null) {
                $inputError = null;
            } else {
                if (!is_string($inputError)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'input_error'));
                }
                $parsedinputError = ErrorCode::tryFrom($inputError);
                $inputError = $parsedinputError instanceof \BackedEnum ? $parsedinputError : $inputError;
            }
        }
        $internalError = null;
        if (array_key_exists('internal_error', $data)) {
            $internalError = $data['internal_error'];
            if ($internalError === null) {
                $internalError = null;
            } else {
                if (!is_string($internalError)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'internal_error'));
                }
                $parsedinternalError = InternalErrorCode::tryFrom($internalError);
                $internalError = $parsedinternalError instanceof \BackedEnum ? $parsedinternalError : $internalError;
            }
        }
        $message = null;
        if (array_key_exists('message', $data)) {
            $message = $data['message'];
            if ($message === null) {
                $message = null;
            } else {
                if (!is_string($message)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'message'));
                }
            }
        }
        return new self(inputError: $inputError, internalError: $internalError, message: $message);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['input_error' => $this->inputError instanceof \BackedEnum ? $this->inputError->value : $this->inputError, 'internal_error' => $this->internalError instanceof \BackedEnum ? $this->internalError->value : $this->internalError, 'message' => $this->message], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
