<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class CheckBody implements \JsonSerializable
{
    public function __construct(
        public CheckRequestTupleKey $tupleKey,
        public ?string $authorizationModelId = null,
        public ?string $consistency = null,
        /** @var array<string, mixed>|null */
        public ?array $context = null,
        public ?ContextualTupleKeys $contextualTuples = null,
        public ?bool $trace = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('tuple_key', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'tuple_key'));
        }
        if (!is_array($data['tuple_key'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'tuple_key'));
        }
        $tupleKey = CheckRequestTupleKey::fromArray($data['tuple_key'], ($path === '' ? '' : $path . '.') . 'tuple_key');
        $authorizationModelId = null;
        if (array_key_exists('authorization_model_id', $data)) {
            $authorizationModelId = $data['authorization_model_id'];
            if ($authorizationModelId === null) {
                $authorizationModelId = null;
            } else {
                if (!is_string($authorizationModelId)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'authorization_model_id'));
                }
            }
        }
        $consistency = null;
        if (array_key_exists('consistency', $data)) {
            $consistency = $data['consistency'];
            if ($consistency === null) {
                $consistency = null;
            } else {
                if (!is_string($consistency)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'consistency'));
                }
                if (!in_array($consistency, [
                    0 => 'UNSPECIFIED',
                    1 => 'MINIMIZE_LATENCY',
                    2 => 'HIGHER_CONSISTENCY',
                ], true)) {
                    throw new FgaResponseDecodeException(sprintf('%s: invalid enum value', ($path === '' ? '' : $path . '.') . 'consistency'));
                }
            }
        }
        $context = null;
        if (array_key_exists('context', $data)) {
            $context = $data['context'];
            if ($context === null) {
                $context = null;
            } else {
                if (!is_array($context)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'context'));
                }
            }
        }
        $contextualTuples = null;
        if (array_key_exists('contextual_tuples', $data)) {
            $contextualTuples = $data['contextual_tuples'];
            if ($contextualTuples === null) {
                $contextualTuples = null;
            } else {
                if (!is_array($contextualTuples)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'contextual_tuples'));
                }
                $contextualTuples = ContextualTupleKeys::fromArray($contextualTuples, ($path === '' ? '' : $path . '.') . 'contextual_tuples');
            }
        }
        $trace = null;
        if (array_key_exists('trace', $data)) {
            $trace = $data['trace'];
            if ($trace === null) {
                $trace = null;
            } else {
                if (!is_bool($trace)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected bool', ($path === '' ? '' : $path . '.') . 'trace'));
                }
            }
        }
        return new self(tupleKey: $tupleKey, authorizationModelId: $authorizationModelId, consistency: $consistency, context: $context, contextualTuples: $contextualTuples, trace: $trace);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['tuple_key' => $this->tupleKey->toArray(), 'authorization_model_id' => $this->authorizationModelId, 'consistency' => $this->consistency, 'context' => $this->context, 'contextual_tuples' => $this->contextualTuples?->toArray(), 'trace' => $this->trace], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
