<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class CheckError implements \JsonSerializable
{
    public function __construct(
        public ?ErrorCode $inputError = null,
        public ?InternalErrorCode $internalError = null,
        public ?string $message = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $inputError = null;
        if (array_key_exists('input_error', $data)) {
            $inputError = $data['input_error'];
            if (!is_string($inputError)) {
                throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'input_error'));
            }
            try {
                $inputError = ErrorCode::from($inputError);
            } catch (\ValueError) {
                throw new FgaValidationException(sprintf('%s: invalid enum value', ($path === '' ? '' : $path . '.') . 'input_error'));
            }
        }
        $internalError = null;
        if (array_key_exists('internal_error', $data)) {
            $internalError = $data['internal_error'];
            if (!is_string($internalError)) {
                throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'internal_error'));
            }
            try {
                $internalError = InternalErrorCode::from($internalError);
            } catch (\ValueError) {
                throw new FgaValidationException(sprintf('%s: invalid enum value', ($path === '' ? '' : $path . '.') . 'internal_error'));
            }
        }
        $message = null;
        if (array_key_exists('message', $data)) {
            $message = $data['message'];
            if (!is_string($message)) {
                throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'message'));
            }
        }
        return new self(inputError: $inputError, internalError: $internalError, message: $message);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['input_error' => $this->inputError?->value, 'internal_error' => $this->internalError?->value, 'message' => $this->message], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
