<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class CheckResponse implements \JsonSerializable
{
    public function __construct(
        public ?bool $allowed = null,
        public ?string $resolution = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $allowed = null;
        if (array_key_exists('allowed', $data)) {
            $allowed = $data['allowed'];
            if ($allowed === null) {
                $allowed = null;
            } else {
                if (!is_bool($allowed)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected bool', ($path === '' ? '' : $path . '.') . 'allowed'));
                }
            }
        }
        $resolution = null;
        if (array_key_exists('resolution', $data)) {
            $resolution = $data['resolution'];
            if ($resolution === null) {
                $resolution = null;
            } else {
                if (!is_string($resolution)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'resolution'));
                }
            }
        }
        return new self(allowed: $allowed, resolution: $resolution);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['allowed' => $this->allowed, 'resolution' => $this->resolution], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
