<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class Computed implements \JsonSerializable
{
    public function __construct(
        public string $userset
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('userset', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'userset'));
        }
        if (!is_string($data['userset'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'userset'));
        }
        $userset = $data['userset'];
        return new self(userset: $userset);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['userset' => $this->userset], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
