<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class ConditionParamTypeRef implements \JsonSerializable
{
    public function __construct(
        public TypeName $typeName,
        /** @var list<ConditionParamTypeRef>|null */
        public ?array $genericTypes = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('type_name', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'type_name'));
        }
        if (!is_string($data['type_name'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'type_name'));
        }
        try {
            $typeName = TypeName::from($data['type_name']);
        } catch (\ValueError) {
            throw new FgaValidationException(sprintf('%s: invalid enum value', ($path === '' ? '' : $path . '.') . 'type_name'));
        }
        $genericTypes = null;
        if (array_key_exists('generic_types', $data)) {
            $genericTypes = $data['generic_types'];
            if (!is_array($genericTypes)) {
                throw new FgaValidationException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'generic_types'));
            }
            $genericTypesList = [];
            foreach ($genericTypes as $idx => $item) {
                if (!is_array($item)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
                }
                $genericTypesList[] = ConditionParamTypeRef::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
            }
            $genericTypes = $genericTypesList;
        }
        return new self(typeName: $typeName, genericTypes: $genericTypes);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['type_name' => $this->typeName->value, 'generic_types' => $this->genericTypes === null ? null : array_map(static fn(ConditionParamTypeRef $v): array => $v->toArray(), $this->genericTypes)], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
