<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class Condition implements \JsonSerializable
{
    public function __construct(
        public string $expression,
        public string $name,
        public ?ConditionMetadata $metadata = null,
        /** @var array<string, mixed>|null */
        public ?array $parameters = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('expression', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'expression'));
        }
        if (!is_string($data['expression'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'expression'));
        }
        $expression = $data['expression'];
        if (!array_key_exists('name', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'name'));
        }
        if (!is_string($data['name'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'name'));
        }
        $name = $data['name'];
        $metadata = null;
        if (array_key_exists('metadata', $data)) {
            $metadata = $data['metadata'];
            if (!is_array($metadata)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'metadata'));
            }
            $metadata = ConditionMetadata::fromArray($metadata, ($path === '' ? '' : $path . '.') . 'metadata');
        }
        $parameters = null;
        if (array_key_exists('parameters', $data)) {
            $parameters = $data['parameters'];
            if (!is_array($parameters)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'parameters'));
            }
        }
        return new self(expression: $expression, name: $name, metadata: $metadata, parameters: $parameters);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['expression' => $this->expression, 'name' => $this->name, 'metadata' => $this->metadata?->toArray(), 'parameters' => $this->parameters], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
