<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class ConditionMetadata implements \JsonSerializable
{
    public function __construct(
        public ?string $module = null,
        public ?SourceInfo $sourceInfo = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $module = null;
        if (array_key_exists('module', $data)) {
            $module = $data['module'];
            if ($module === null) {
                $module = null;
            } else {
                if (!is_string($module)) {
                    throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'module'));
                }
            }
        }
        $sourceInfo = null;
        if (array_key_exists('source_info', $data)) {
            $sourceInfo = $data['source_info'];
            if ($sourceInfo === null) {
                $sourceInfo = null;
            } else {
                if (!is_array($sourceInfo)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'source_info'));
                }
                $sourceInfo = SourceInfo::fromArray($sourceInfo, ($path === '' ? '' : $path . '.') . 'source_info');
            }
        }
        return new self(module: $module, sourceInfo: $sourceInfo);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['module' => $this->module, 'source_info' => $this->sourceInfo?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
