<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

enum ConsistencyPreference: string
{
    case UNSPECIFIED = 'UNSPECIFIED';
    case MINIMIZE_LATENCY = 'MINIMIZE_LATENCY';
    case HIGHER_CONSISTENCY = 'HIGHER_CONSISTENCY';
}
