<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class ContextualTupleKeys implements \JsonSerializable
{
    public function __construct(
        /** @var list<TupleKey> */
        public array $tupleKeys
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('tuple_keys', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'tuple_keys'));
        }
        if (!is_array($data['tuple_keys'])) {
            throw new FgaValidationException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'tuple_keys'));
        }
        $tupleKeysList = [];
        foreach ($data['tuple_keys'] as $idx => $item) {
            if (!is_array($item)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
            }
            $tupleKeysList[] = TupleKey::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
        }
        $tupleKeys = $tupleKeysList;
        return new self(tupleKeys: $tupleKeys);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['tuple_keys' => array_map(static fn(TupleKey $v): array => $v->toArray(), $this->tupleKeys)], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
