<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

enum ErrorCode: string
{
    case NO_ERROR = 'no_error';
    case VALIDATION_ERROR = 'validation_error';
    case AUTHORIZATION_MODEL_NOT_FOUND = 'authorization_model_not_found';
    case AUTHORIZATION_MODEL_RESOLUTION_TOO_COMPLEX = 'authorization_model_resolution_too_complex';
    case INVALID_WRITE_INPUT = 'invalid_write_input';
    case CANNOT_ALLOW_DUPLICATE_TUPLES_IN_ONE_REQUEST = 'cannot_allow_duplicate_tuples_in_one_request';
    case CANNOT_ALLOW_DUPLICATE_TYPES_IN_ONE_REQUEST = 'cannot_allow_duplicate_types_in_one_request';
    case CANNOT_ALLOW_MULTIPLE_REFERENCES_TO_ONE_RELATION = 'cannot_allow_multiple_references_to_one_relation';
    case INVALID_CONTINUATION_TOKEN = 'invalid_continuation_token';
    case INVALID_TUPLE_SET = 'invalid_tuple_set';
    case INVALID_CHECK_INPUT = 'invalid_check_input';
    case INVALID_EXPAND_INPUT = 'invalid_expand_input';
    case UNSUPPORTED_USER_SET = 'unsupported_user_set';
    case INVALID_OBJECT_FORMAT = 'invalid_object_format';
    case WRITE_FAILED_DUE_TO_INVALID_INPUT = 'write_failed_due_to_invalid_input';
    case AUTHORIZATION_MODEL_ASSERTIONS_NOT_FOUND = 'authorization_model_assertions_not_found';
    case LATEST_AUTHORIZATION_MODEL_NOT_FOUND = 'latest_authorization_model_not_found';
    case TYPE_NOT_FOUND = 'type_not_found';
    case RELATION_NOT_FOUND = 'relation_not_found';
    case EMPTY_RELATION_DEFINITION = 'empty_relation_definition';
    case INVALID_USER = 'invalid_user';
    case INVALID_TUPLE = 'invalid_tuple';
    case UNKNOWN_RELATION = 'unknown_relation';
    case STORE_ID_INVALID_LENGTH = 'store_id_invalid_length';
    case ASSERTIONS_TOO_MANY_ITEMS = 'assertions_too_many_items';
    case ID_TOO_LONG = 'id_too_long';
    case AUTHORIZATION_MODEL_ID_TOO_LONG = 'authorization_model_id_too_long';
    case TUPLE_KEY_VALUE_NOT_SPECIFIED = 'tuple_key_value_not_specified';
    case TUPLE_KEYS_TOO_MANY_OR_TOO_FEW_ITEMS = 'tuple_keys_too_many_or_too_few_items';
    case PAGE_SIZE_INVALID = 'page_size_invalid';
    case PARAM_MISSING_VALUE = 'param_missing_value';
    case DIFFERENCE_BASE_MISSING_VALUE = 'difference_base_missing_value';
    case SUBTRACT_BASE_MISSING_VALUE = 'subtract_base_missing_value';
    case OBJECT_TOO_LONG = 'object_too_long';
    case RELATION_TOO_LONG = 'relation_too_long';
    case TYPE_DEFINITIONS_TOO_FEW_ITEMS = 'type_definitions_too_few_items';
    case TYPE_INVALID_LENGTH = 'type_invalid_length';
    case TYPE_INVALID_PATTERN = 'type_invalid_pattern';
    case RELATIONS_TOO_FEW_ITEMS = 'relations_too_few_items';
    case RELATIONS_TOO_LONG = 'relations_too_long';
    case RELATIONS_INVALID_PATTERN = 'relations_invalid_pattern';
    case OBJECT_INVALID_PATTERN = 'object_invalid_pattern';
    case QUERY_STRING_TYPE_CONTINUATION_TOKEN_MISMATCH = 'query_string_type_continuation_token_mismatch';
    case EXCEEDED_ENTITY_LIMIT = 'exceeded_entity_limit';
    case INVALID_CONTEXTUAL_TUPLE = 'invalid_contextual_tuple';
    case DUPLICATE_CONTEXTUAL_TUPLE = 'duplicate_contextual_tuple';
    case INVALID_AUTHORIZATION_MODEL = 'invalid_authorization_model';
    case UNSUPPORTED_SCHEMA_VERSION = 'unsupported_schema_version';
    case CANCELLED = 'cancelled';
    case INVALID_START_TIME = 'invalid_start_time';
}
