<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class ExpandResponse implements \JsonSerializable
{
    public function __construct(
        public ?UsersetTree $tree = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $tree = null;
        if (array_key_exists('tree', $data)) {
            $tree = $data['tree'];
            if (!is_array($tree)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'tree'));
            }
            $tree = UsersetTree::fromArray($tree, ($path === '' ? '' : $path . '.') . 'tree');
        }
        return new self(tree: $tree);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['tree' => $this->tree?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
