<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class FgaObject implements \JsonSerializable
{
    public function __construct(
        public string $id,
        public string $type
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('id', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'id'));
        }
        if (!is_string($data['id'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'id'));
        }
        $id = $data['id'];
        if (!array_key_exists('type', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'type'));
        }
        if (!is_string($data['type'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'type'));
        }
        $type = $data['type'];
        return new self(id: $id, type: $type);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['id' => $this->id, 'type' => $this->type], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
