<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class ForbiddenResponse implements \JsonSerializable
{
    public function __construct(
        public AuthErrorCode|string|null $code = null,
        public ?string $message = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $code = null;
        if (array_key_exists('code', $data)) {
            $code = $data['code'];
            if ($code === null) {
                $code = null;
            } else {
                if (!is_string($code)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'code'));
                }
                $parsedcode = AuthErrorCode::tryFrom($code);
                $code = $parsedcode instanceof \BackedEnum ? $parsedcode : $code;
            }
        }
        $message = null;
        if (array_key_exists('message', $data)) {
            $message = $data['message'];
            if ($message === null) {
                $message = null;
            } else {
                if (!is_string($message)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'message'));
                }
            }
        }
        return new self(code: $code, message: $message);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['code' => $this->code instanceof \BackedEnum ? $this->code->value : $this->code, 'message' => $this->message], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
