<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class ForbiddenResponse implements \JsonSerializable
{
    public function __construct(
        public ?AuthErrorCode $code = null,
        public ?string $message = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $code = null;
        if (array_key_exists('code', $data)) {
            $code = $data['code'];
            if (!is_string($code)) {
                throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'code'));
            }
            try {
                $code = AuthErrorCode::from($code);
            } catch (\ValueError) {
                throw new FgaValidationException(sprintf('%s: invalid enum value', ($path === '' ? '' : $path . '.') . 'code'));
            }
        }
        $message = null;
        if (array_key_exists('message', $data)) {
            $message = $data['message'];
            if (!is_string($message)) {
                throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'message'));
            }
        }
        return new self(code: $code, message: $message);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['code' => $this->code?->value, 'message' => $this->message], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
