<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class GetStoreResponse implements \JsonSerializable
{
    public function __construct(
        public \DateTimeImmutable $createdAt,
        public string $id,
        public string $name,
        public \DateTimeImmutable $updatedAt,
        public ?\DateTimeImmutable $deletedAt = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('created_at', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'created_at'));
        }
        if (!is_string($data['created_at'])) {
            throw new FgaValidationException(sprintf('%s: expected date-time string', ($path === '' ? '' : $path . '.') . 'created_at'));
        }
        $createdAt = new \DateTimeImmutable($data['created_at']);
        if (!array_key_exists('id', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'id'));
        }
        if (!is_string($data['id'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'id'));
        }
        $id = $data['id'];
        if (!array_key_exists('name', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'name'));
        }
        if (!is_string($data['name'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'name'));
        }
        $name = $data['name'];
        if (!array_key_exists('updated_at', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'updated_at'));
        }
        if (!is_string($data['updated_at'])) {
            throw new FgaValidationException(sprintf('%s: expected date-time string', ($path === '' ? '' : $path . '.') . 'updated_at'));
        }
        $updatedAt = new \DateTimeImmutable($data['updated_at']);
        $deletedAt = null;
        if (array_key_exists('deleted_at', $data)) {
            $deletedAt = $data['deleted_at'];
            if ($deletedAt === null) {
                $deletedAt = null;
            } else {
                if (!is_string($deletedAt)) {
                    throw new FgaValidationException(sprintf('%s: expected date-time string', ($path === '' ? '' : $path . '.') . 'deleted_at'));
                }
                $deletedAt = new \DateTimeImmutable($deletedAt);
            }
        }
        return new self(createdAt: $createdAt, id: $id, name: $name, updatedAt: $updatedAt, deletedAt: $deletedAt);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['created_at' => $this->createdAt->format(\DateTimeInterface::ATOM), 'id' => $this->id, 'name' => $this->name, 'updated_at' => $this->updatedAt->format(\DateTimeInterface::ATOM), 'deleted_at' => $this->deletedAt->format(\DateTimeInterface::ATOM)], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
