<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

enum InternalErrorCode: string
{
    case NO_INTERNAL_ERROR = 'no_internal_error';
    case INTERNAL_ERROR = 'internal_error';
    case DEADLINE_EXCEEDED = 'deadline_exceeded';
    case ALREADY_EXISTS = 'already_exists';
    case RESOURCE_EXHAUSTED = 'resource_exhausted';
    case FAILED_PRECONDITION = 'failed_precondition';
    case ABORTED = 'aborted';
    case OUT_OF_RANGE = 'out_of_range';
    case UNAVAILABLE = 'unavailable';
    case DATA_LOSS = 'data_loss';
}
