<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class Leaf implements \JsonSerializable
{
    public function __construct(
        public ?Computed $computed = null,
        public ?UsersetTreeTupleToUserset $tupleToUserset = null,
        public ?Users $users = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $computed = null;
        if (array_key_exists('computed', $data)) {
            $computed = $data['computed'];
            if ($computed === null) {
                $computed = null;
            } else {
                if (!is_array($computed)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'computed'));
                }
                $computed = Computed::fromArray($computed, ($path === '' ? '' : $path . '.') . 'computed');
            }
        }
        $tupleToUserset = null;
        if (array_key_exists('tupleToUserset', $data)) {
            $tupleToUserset = $data['tupleToUserset'];
            if ($tupleToUserset === null) {
                $tupleToUserset = null;
            } else {
                if (!is_array($tupleToUserset)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'tupleToUserset'));
                }
                $tupleToUserset = UsersetTreeTupleToUserset::fromArray($tupleToUserset, ($path === '' ? '' : $path . '.') . 'tupleToUserset');
            }
        }
        $users = null;
        if (array_key_exists('users', $data)) {
            $users = $data['users'];
            if ($users === null) {
                $users = null;
            } else {
                if (!is_array($users)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'users'));
                }
                $users = Users::fromArray($users, ($path === '' ? '' : $path . '.') . 'users');
            }
        }
        return new self(computed: $computed, tupleToUserset: $tupleToUserset, users: $users);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['computed' => $this->computed?->toArray(), 'tupleToUserset' => $this->tupleToUserset?->toArray(), 'users' => $this->users?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
