<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class ListObjectsResponse implements \JsonSerializable
{
    public function __construct(
        /** @var list<mixed> */
        public array $objects
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('objects', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'objects'));
        }
        if (!is_array($data['objects'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'objects'));
        }
        $objectsList = [];
        foreach ($data['objects'] as $idx => $item) {
            if (!is_string($item)) {
                throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . $idx));
            }
            $objectsList[] = $item;
        }
        $objects = $objectsList;
        return new self(objects: $objects);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['objects' => $this->objects], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
