<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class ListStoresResponse implements \JsonSerializable
{
    public function __construct(
        public string $continuationToken,
        /** @var list<Store> */
        public array $stores
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('continuation_token', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'continuation_token'));
        }
        if (!is_string($data['continuation_token'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'continuation_token'));
        }
        $continuationToken = $data['continuation_token'];
        if (!array_key_exists('stores', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'stores'));
        }
        if (!is_array($data['stores'])) {
            throw new FgaValidationException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'stores'));
        }
        $storesList = [];
        foreach ($data['stores'] as $idx => $item) {
            if (!is_array($item)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
            }
            $storesList[] = Store::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
        }
        $stores = $storesList;
        return new self(continuationToken: $continuationToken, stores: $stores);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['continuation_token' => $this->continuationToken, 'stores' => array_map(static fn(Store $v): array => $v->toArray(), $this->stores)], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
