<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class ListUsersBody implements \JsonSerializable
{
    public function __construct(
        public FgaObject $object,
        public string $relation,
        /** @var list<UserTypeFilter> */
        public array $userFilters,
        public ?string $authorizationModelId = null,
        public ?string $consistency = null,
        /** @var array<string, mixed>|null */
        public ?array $context = null,
        /** @var list<TupleKey>|null */
        public ?array $contextualTuples = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('object', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'object'));
        }
        if (!is_array($data['object'])) {
            throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'object'));
        }
        $object = FgaObject::fromArray($data['object'], ($path === '' ? '' : $path . '.') . 'object');
        if (!array_key_exists('relation', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'relation'));
        }
        if (!is_string($data['relation'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'relation'));
        }
        $relation = $data['relation'];
        if (!array_key_exists('user_filters', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'user_filters'));
        }
        if (!is_array($data['user_filters'])) {
            throw new FgaValidationException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'user_filters'));
        }
        $userFiltersList = [];
        foreach ($data['user_filters'] as $idx => $item) {
            if (!is_array($item)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
            }
            $userFiltersList[] = UserTypeFilter::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
        }
        $userFilters = $userFiltersList;
        $authorizationModelId = null;
        if (array_key_exists('authorization_model_id', $data)) {
            $authorizationModelId = $data['authorization_model_id'];
            if (!is_string($authorizationModelId)) {
                throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'authorization_model_id'));
            }
        }
        $consistency = null;
        if (array_key_exists('consistency', $data)) {
            $consistency = $data['consistency'];
            if (!is_string($consistency)) {
                throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'consistency'));
            }
            if (!in_array($consistency, [
                0 => 'UNSPECIFIED',
                1 => 'MINIMIZE_LATENCY',
                2 => 'HIGHER_CONSISTENCY',
            ], true)) {
                throw new FgaValidationException(sprintf('%s: invalid enum value', ($path === '' ? '' : $path . '.') . 'consistency'));
            }
        }
        $context = null;
        if (array_key_exists('context', $data)) {
            $context = $data['context'];
            if (!is_array($context)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'context'));
            }
        }
        $contextualTuples = null;
        if (array_key_exists('contextual_tuples', $data)) {
            $contextualTuples = $data['contextual_tuples'];
            if (!is_array($contextualTuples)) {
                throw new FgaValidationException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'contextual_tuples'));
            }
            $contextualTuplesList = [];
            foreach ($contextualTuples as $idx => $item) {
                if (!is_array($item)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
                }
                $contextualTuplesList[] = TupleKey::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
            }
            $contextualTuples = $contextualTuplesList;
        }
        return new self(object: $object, relation: $relation, userFilters: $userFilters, authorizationModelId: $authorizationModelId, consistency: $consistency, context: $context, contextualTuples: $contextualTuples);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['object' => $this->object->toArray(), 'relation' => $this->relation, 'user_filters' => array_map(static fn(UserTypeFilter $v): array => $v->toArray(), $this->userFilters), 'authorization_model_id' => $this->authorizationModelId, 'consistency' => $this->consistency, 'context' => $this->context, 'contextual_tuples' => $this->contextualTuples === null ? null : array_map(static fn(TupleKey $v): array => $v->toArray(), $this->contextualTuples)], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
