<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class ListUsersResponse implements \JsonSerializable
{
    public function __construct(
        /** @var list<User> */
        public array $users
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('users', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'users'));
        }
        if (!is_array($data['users'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'users'));
        }
        $usersList = [];
        foreach ($data['users'] as $idx => $item) {
            if (!is_array($item)) {
                throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
            }
            $usersList[] = User::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
        }
        $users = $usersList;
        return new self(users: $users);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['users' => array_map(static fn(User $v): array => $v->toArray(), $this->users)], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
