<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class Metadata implements \JsonSerializable
{
    public function __construct(
        public ?string $module = null,
        /** @var array<string, mixed>|null */
        public ?array $relations = null,
        public ?SourceInfo $sourceInfo = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $module = null;
        if (array_key_exists('module', $data)) {
            $module = $data['module'];
            if (!is_string($module)) {
                throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'module'));
            }
        }
        $relations = null;
        if (array_key_exists('relations', $data)) {
            $relations = $data['relations'];
            if (!is_array($relations)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'relations'));
            }
        }
        $sourceInfo = null;
        if (array_key_exists('source_info', $data)) {
            $sourceInfo = $data['source_info'];
            if (!is_array($sourceInfo)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'source_info'));
            }
            $sourceInfo = SourceInfo::fromArray($sourceInfo, ($path === '' ? '' : $path . '.') . 'source_info');
        }
        return new self(module: $module, relations: $relations, sourceInfo: $sourceInfo);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['module' => $this->module, 'relations' => $this->relations, 'source_info' => $this->sourceInfo?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
