<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class Node implements \JsonSerializable
{
    public function __construct(
        public string $name,
        public ?UsersetTreeDifference $difference = null,
        public ?Nodes $intersection = null,
        public ?Leaf $leaf = null,
        public ?Nodes $union = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('name', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'name'));
        }
        if (!is_string($data['name'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'name'));
        }
        $name = $data['name'];
        $difference = null;
        if (array_key_exists('difference', $data)) {
            $difference = $data['difference'];
            if ($difference === null) {
                $difference = null;
            } else {
                if (!is_array($difference)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'difference'));
                }
                $difference = UsersetTreeDifference::fromArray($difference, ($path === '' ? '' : $path . '.') . 'difference');
            }
        }
        $intersection = null;
        if (array_key_exists('intersection', $data)) {
            $intersection = $data['intersection'];
            if ($intersection === null) {
                $intersection = null;
            } else {
                if (!is_array($intersection)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'intersection'));
                }
                $intersection = Nodes::fromArray($intersection, ($path === '' ? '' : $path . '.') . 'intersection');
            }
        }
        $leaf = null;
        if (array_key_exists('leaf', $data)) {
            $leaf = $data['leaf'];
            if ($leaf === null) {
                $leaf = null;
            } else {
                if (!is_array($leaf)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'leaf'));
                }
                $leaf = Leaf::fromArray($leaf, ($path === '' ? '' : $path . '.') . 'leaf');
            }
        }
        $union = null;
        if (array_key_exists('union', $data)) {
            $union = $data['union'];
            if ($union === null) {
                $union = null;
            } else {
                if (!is_array($union)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'union'));
                }
                $union = Nodes::fromArray($union, ($path === '' ? '' : $path . '.') . 'union');
            }
        }
        return new self(name: $name, difference: $difference, intersection: $intersection, leaf: $leaf, union: $union);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['name' => $this->name, 'difference' => $this->difference?->toArray(), 'intersection' => $this->intersection?->toArray(), 'leaf' => $this->leaf?->toArray(), 'union' => $this->union?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
