<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class Nodes implements \JsonSerializable
{
    public function __construct(
        /** @var list<Node> */
        public array $nodes
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('nodes', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'nodes'));
        }
        if (!is_array($data['nodes'])) {
            throw new FgaValidationException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'nodes'));
        }
        $nodesList = [];
        foreach ($data['nodes'] as $idx => $item) {
            if (!is_array($item)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
            }
            $nodesList[] = Node::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
        }
        $nodes = $nodesList;
        return new self(nodes: $nodes);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['nodes' => array_map(static fn(Node $v): array => $v->toArray(), $this->nodes)], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
