<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

enum NotFoundErrorCode: string
{
    case NO_NOT_FOUND_ERROR = 'no_not_found_error';
    case UNDEFINED_ENDPOINT = 'undefined_endpoint';
    case STORE_ID_NOT_FOUND = 'store_id_not_found';
    case UNIMPLEMENTED = 'unimplemented';
}
