<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class ReadResponse implements \JsonSerializable
{
    public function __construct(
        public string $continuationToken,
        /** @var list<Tuple> */
        public array $tuples
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('continuation_token', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'continuation_token'));
        }
        if (!is_string($data['continuation_token'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'continuation_token'));
        }
        $continuationToken = $data['continuation_token'];
        if (!array_key_exists('tuples', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'tuples'));
        }
        if (!is_array($data['tuples'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'tuples'));
        }
        $tuplesList = [];
        foreach ($data['tuples'] as $idx => $item) {
            if (!is_array($item)) {
                throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
            }
            $tuplesList[] = Tuple::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
        }
        $tuples = $tuplesList;
        return new self(continuationToken: $continuationToken, tuples: $tuples);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['continuation_token' => $this->continuationToken, 'tuples' => array_map(static fn(Tuple $v): array => $v->toArray(), $this->tuples)], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
