<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class ReadRequestTupleKey implements \JsonSerializable
{
    public function __construct(
        public ?string $object = null,
        public ?string $relation = null,
        public ?string $user = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $object = null;
        if (array_key_exists('object', $data)) {
            $object = $data['object'];
            if ($object === null) {
                $object = null;
            } else {
                if (!is_string($object)) {
                    throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'object'));
                }
            }
        }
        $relation = null;
        if (array_key_exists('relation', $data)) {
            $relation = $data['relation'];
            if ($relation === null) {
                $relation = null;
            } else {
                if (!is_string($relation)) {
                    throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'relation'));
                }
            }
        }
        $user = null;
        if (array_key_exists('user', $data)) {
            $user = $data['user'];
            if ($user === null) {
                $user = null;
            } else {
                if (!is_string($user)) {
                    throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'user'));
                }
            }
        }
        return new self(object: $object, relation: $relation, user: $user);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['object' => $this->object, 'relation' => $this->relation, 'user' => $this->user], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
