<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class ReadBody implements \JsonSerializable
{
    public function __construct(
        public ?string $consistency = null,
        public ?string $continuationToken = null,
        public ?int $pageSize = null,
        public ?ReadRequestTupleKey $tupleKey = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $consistency = null;
        if (array_key_exists('consistency', $data)) {
            $consistency = $data['consistency'];
            if ($consistency === null) {
                $consistency = null;
            } else {
                if (!is_string($consistency)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'consistency'));
                }
                if (!in_array($consistency, [
                    0 => 'UNSPECIFIED',
                    1 => 'MINIMIZE_LATENCY',
                    2 => 'HIGHER_CONSISTENCY',
                ], true)) {
                    throw new FgaResponseDecodeException(sprintf('%s: invalid enum value', ($path === '' ? '' : $path . '.') . 'consistency'));
                }
            }
        }
        $continuationToken = null;
        if (array_key_exists('continuation_token', $data)) {
            $continuationToken = $data['continuation_token'];
            if ($continuationToken === null) {
                $continuationToken = null;
            } else {
                if (!is_string($continuationToken)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'continuation_token'));
                }
            }
        }
        $pageSize = null;
        if (array_key_exists('page_size', $data)) {
            $pageSize = $data['page_size'];
            if ($pageSize === null) {
                $pageSize = null;
            } else {
                if (!is_integer($pageSize)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected int', ($path === '' ? '' : $path . '.') . 'page_size'));
                }
            }
        }
        $tupleKey = null;
        if (array_key_exists('tuple_key', $data)) {
            $tupleKey = $data['tuple_key'];
            if ($tupleKey === null) {
                $tupleKey = null;
            } else {
                if (!is_array($tupleKey)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'tuple_key'));
                }
                $tupleKey = ReadRequestTupleKey::fromArray($tupleKey, ($path === '' ? '' : $path . '.') . 'tuple_key');
            }
        }
        return new self(consistency: $consistency, continuationToken: $continuationToken, pageSize: $pageSize, tupleKey: $tupleKey);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['consistency' => $this->consistency, 'continuation_token' => $this->continuationToken, 'page_size' => $this->pageSize, 'tuple_key' => $this->tupleKey?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
