<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class ReadAssertionsResponse implements \JsonSerializable
{
    public function __construct(
        public string $authorizationModelId,
        /** @var list<Assertion>|null */
        public ?array $assertions = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('authorization_model_id', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'authorization_model_id'));
        }
        if (!is_string($data['authorization_model_id'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'authorization_model_id'));
        }
        $authorizationModelId = $data['authorization_model_id'];
        $assertions = null;
        if (array_key_exists('assertions', $data)) {
            $assertions = $data['assertions'];
            if (!is_array($assertions)) {
                throw new FgaValidationException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'assertions'));
            }
            $assertionsList = [];
            foreach ($assertions as $idx => $item) {
                if (!is_array($item)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
                }
                $assertionsList[] = Assertion::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
            }
            $assertions = $assertionsList;
        }
        return new self(authorizationModelId: $authorizationModelId, assertions: $assertions);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['authorization_model_id' => $this->authorizationModelId, 'assertions' => $this->assertions === null ? null : array_map(static fn(Assertion $v): array => $v->toArray(), $this->assertions)], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
