<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class ReadChangesResponse implements \JsonSerializable
{
    public function __construct(
        /** @var list<TupleChange> */
        public array $changes,
        public ?string $continuationToken = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('changes', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'changes'));
        }
        if (!is_array($data['changes'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'changes'));
        }
        $changesList = [];
        foreach ($data['changes'] as $idx => $item) {
            if (!is_array($item)) {
                throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
            }
            $changesList[] = TupleChange::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
        }
        $changes = $changesList;
        $continuationToken = null;
        if (array_key_exists('continuation_token', $data)) {
            $continuationToken = $data['continuation_token'];
            if ($continuationToken === null) {
                $continuationToken = null;
            } else {
                if (!is_string($continuationToken)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'continuation_token'));
                }
            }
        }
        return new self(changes: $changes, continuationToken: $continuationToken);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['changes' => array_map(static fn(TupleChange $v): array => $v->toArray(), $this->changes), 'continuation_token' => $this->continuationToken], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
