<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class ReadAuthorizationModelResponse implements \JsonSerializable
{
    public function __construct(
        public ?AuthorizationModel $authorizationModel = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $authorizationModel = null;
        if (array_key_exists('authorization_model', $data)) {
            $authorizationModel = $data['authorization_model'];
            if ($authorizationModel === null) {
                $authorizationModel = null;
            } else {
                if (!is_array($authorizationModel)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'authorization_model'));
                }
                $authorizationModel = AuthorizationModel::fromArray($authorizationModel, ($path === '' ? '' : $path . '.') . 'authorization_model');
            }
        }
        return new self(authorizationModel: $authorizationModel);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['authorization_model' => $this->authorizationModel?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
