<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class ReadAuthorizationModelsResponse implements \JsonSerializable
{
    public function __construct(
        /** @var list<AuthorizationModel> */
        public array $authorizationModels,
        public ?string $continuationToken = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('authorization_models', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'authorization_models'));
        }
        if (!is_array($data['authorization_models'])) {
            throw new FgaValidationException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'authorization_models'));
        }
        $authorizationModelsList = [];
        foreach ($data['authorization_models'] as $idx => $item) {
            if (!is_array($item)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
            }
            $authorizationModelsList[] = AuthorizationModel::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
        }
        $authorizationModels = $authorizationModelsList;
        $continuationToken = null;
        if (array_key_exists('continuation_token', $data)) {
            $continuationToken = $data['continuation_token'];
            if ($continuationToken === null) {
                $continuationToken = null;
            } else {
                if (!is_string($continuationToken)) {
                    throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'continuation_token'));
                }
            }
        }
        return new self(authorizationModels: $authorizationModels, continuationToken: $continuationToken);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['authorization_models' => array_map(static fn(AuthorizationModel $v): array => $v->toArray(), $this->authorizationModels), 'continuation_token' => $this->continuationToken], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
