<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class RelationReference implements \JsonSerializable
{
    public function __construct(
        public string $type,
        public ?string $condition = null,
        public ?string $relation = null,
        /** @var array<string, mixed>|null */
        public ?array $wildcard = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('type', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'type'));
        }
        if (!is_string($data['type'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'type'));
        }
        $type = $data['type'];
        $condition = null;
        if (array_key_exists('condition', $data)) {
            $condition = $data['condition'];
            if ($condition === null) {
                $condition = null;
            } else {
                if (!is_string($condition)) {
                    throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'condition'));
                }
            }
        }
        $relation = null;
        if (array_key_exists('relation', $data)) {
            $relation = $data['relation'];
            if ($relation === null) {
                $relation = null;
            } else {
                if (!is_string($relation)) {
                    throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'relation'));
                }
            }
        }
        $wildcard = null;
        if (array_key_exists('wildcard', $data)) {
            $wildcard = $data['wildcard'];
            if ($wildcard === null) {
                $wildcard = null;
            } else {
                if (!is_array($wildcard)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'wildcard'));
                }
            }
        }
        return new self(type: $type, condition: $condition, relation: $relation, wildcard: $wildcard);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['type' => $this->type, 'condition' => $this->condition, 'relation' => $this->relation, 'wildcard' => $this->wildcard], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
