<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class RelationMetadata implements \JsonSerializable
{
    public function __construct(
        /** @var list<RelationReference>|null */
        public ?array $directlyRelatedUserTypes = null,
        public ?string $module = null,
        public ?SourceInfo $sourceInfo = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $directlyRelatedUserTypes = null;
        if (array_key_exists('directly_related_user_types', $data)) {
            $directlyRelatedUserTypes = $data['directly_related_user_types'];
            if (!is_array($directlyRelatedUserTypes)) {
                throw new FgaValidationException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'directly_related_user_types'));
            }
            $directlyRelatedUserTypesList = [];
            foreach ($directlyRelatedUserTypes as $idx => $item) {
                if (!is_array($item)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
                }
                $directlyRelatedUserTypesList[] = RelationReference::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
            }
            $directlyRelatedUserTypes = $directlyRelatedUserTypesList;
        }
        $module = null;
        if (array_key_exists('module', $data)) {
            $module = $data['module'];
            if (!is_string($module)) {
                throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'module'));
            }
        }
        $sourceInfo = null;
        if (array_key_exists('source_info', $data)) {
            $sourceInfo = $data['source_info'];
            if (!is_array($sourceInfo)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'source_info'));
            }
            $sourceInfo = SourceInfo::fromArray($sourceInfo, ($path === '' ? '' : $path . '.') . 'source_info');
        }
        return new self(directlyRelatedUserTypes: $directlyRelatedUserTypes, module: $module, sourceInfo: $sourceInfo);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['directly_related_user_types' => $this->directlyRelatedUserTypes === null ? null : array_map(static fn(RelationReference $v): array => $v->toArray(), $this->directlyRelatedUserTypes), 'module' => $this->module, 'source_info' => $this->sourceInfo?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
