<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class RelationshipCondition implements \JsonSerializable
{
    public function __construct(
        public string $name,
        /** @var array<string, mixed>|null */
        public ?array $context = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('name', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'name'));
        }
        if (!is_string($data['name'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'name'));
        }
        $name = $data['name'];
        $context = null;
        if (array_key_exists('context', $data)) {
            $context = $data['context'];
            if ($context === null) {
                $context = null;
            } else {
                if (!is_array($context)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'context'));
                }
            }
        }
        return new self(name: $name, context: $context);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['name' => $this->name, 'context' => $this->context], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
