<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class SourceInfo implements \JsonSerializable
{
    public function __construct(
        public ?string $file = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $file = null;
        if (array_key_exists('file', $data)) {
            $file = $data['file'];
            if ($file === null) {
                $file = null;
            } else {
                if (!is_string($file)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'file'));
                }
            }
        }
        return new self(file: $file);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['file' => $this->file], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
