<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class Status implements \JsonSerializable
{
    public function __construct(
        public ?int $code = null,
        /** @var list<Any>|null */
        public ?array $details = null,
        public ?string $message = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $code = null;
        if (array_key_exists('code', $data)) {
            $code = $data['code'];
            if (!is_integer($code)) {
                throw new FgaValidationException(sprintf('%s: expected int', ($path === '' ? '' : $path . '.') . 'code'));
            }
        }
        $details = null;
        if (array_key_exists('details', $data)) {
            $details = $data['details'];
            if (!is_array($details)) {
                throw new FgaValidationException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'details'));
            }
            $detailsList = [];
            foreach ($details as $idx => $item) {
                if (!is_array($item)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
                }
                $detailsList[] = Any::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
            }
            $details = $detailsList;
        }
        $message = null;
        if (array_key_exists('message', $data)) {
            $message = $data['message'];
            if (!is_string($message)) {
                throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'message'));
            }
        }
        return new self(code: $code, details: $details, message: $message);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['code' => $this->code, 'details' => $this->details === null ? null : array_map(static fn(Any $v): array => $v->toArray(), $this->details), 'message' => $this->message], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
