<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class StreamedListObjectsBody implements \JsonSerializable
{
    public function __construct(
        public string $relation,
        public string $type,
        public string $user,
        public ?string $authorizationModelId = null,
        public ?string $consistency = null,
        /** @var array<string, mixed>|null */
        public ?array $context = null,
        public ?ContextualTupleKeys $contextualTuples = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('relation', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'relation'));
        }
        if (!is_string($data['relation'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'relation'));
        }
        $relation = $data['relation'];
        if (!array_key_exists('type', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'type'));
        }
        if (!is_string($data['type'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'type'));
        }
        $type = $data['type'];
        if (!array_key_exists('user', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'user'));
        }
        if (!is_string($data['user'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'user'));
        }
        $user = $data['user'];
        $authorizationModelId = null;
        if (array_key_exists('authorization_model_id', $data)) {
            $authorizationModelId = $data['authorization_model_id'];
            if (!is_string($authorizationModelId)) {
                throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'authorization_model_id'));
            }
        }
        $consistency = null;
        if (array_key_exists('consistency', $data)) {
            $consistency = $data['consistency'];
            if (!is_string($consistency)) {
                throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'consistency'));
            }
            if (!in_array($consistency, [
                0 => 'UNSPECIFIED',
                1 => 'MINIMIZE_LATENCY',
                2 => 'HIGHER_CONSISTENCY',
            ], true)) {
                throw new FgaValidationException(sprintf('%s: invalid enum value', ($path === '' ? '' : $path . '.') . 'consistency'));
            }
        }
        $context = null;
        if (array_key_exists('context', $data)) {
            $context = $data['context'];
            if (!is_array($context)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'context'));
            }
        }
        $contextualTuples = null;
        if (array_key_exists('contextual_tuples', $data)) {
            $contextualTuples = $data['contextual_tuples'];
            if (!is_array($contextualTuples)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'contextual_tuples'));
            }
            $contextualTuples = ContextualTupleKeys::fromArray($contextualTuples, ($path === '' ? '' : $path . '.') . 'contextual_tuples');
        }
        return new self(relation: $relation, type: $type, user: $user, authorizationModelId: $authorizationModelId, consistency: $consistency, context: $context, contextualTuples: $contextualTuples);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['relation' => $this->relation, 'type' => $this->type, 'user' => $this->user, 'authorization_model_id' => $this->authorizationModelId, 'consistency' => $this->consistency, 'context' => $this->context, 'contextual_tuples' => $this->contextualTuples?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
