<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class TupleToUserset implements \JsonSerializable
{
    public function __construct(
        public ObjectRelation $computedUserset,
        public ObjectRelation $tupleset
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('computedUserset', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'computedUserset'));
        }
        if (!is_array($data['computedUserset'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'computedUserset'));
        }
        $computedUserset = ObjectRelation::fromArray($data['computedUserset'], ($path === '' ? '' : $path . '.') . 'computedUserset');
        if (!array_key_exists('tupleset', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'tupleset'));
        }
        if (!is_array($data['tupleset'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'tupleset'));
        }
        $tupleset = ObjectRelation::fromArray($data['tupleset'], ($path === '' ? '' : $path . '.') . 'tupleset');
        return new self(computedUserset: $computedUserset, tupleset: $tupleset);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['computedUserset' => $this->computedUserset->toArray(), 'tupleset' => $this->tupleset->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
