<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class TupleKey implements \JsonSerializable
{
    public function __construct(
        public string $object,
        public string $relation,
        public string $user,
        public ?RelationshipCondition $condition = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('object', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'object'));
        }
        if (!is_string($data['object'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'object'));
        }
        $object = $data['object'];
        if (!array_key_exists('relation', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'relation'));
        }
        if (!is_string($data['relation'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'relation'));
        }
        $relation = $data['relation'];
        if (!array_key_exists('user', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'user'));
        }
        if (!is_string($data['user'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'user'));
        }
        $user = $data['user'];
        $condition = null;
        if (array_key_exists('condition', $data)) {
            $condition = $data['condition'];
            if ($condition === null) {
                $condition = null;
            } else {
                if (!is_array($condition)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'condition'));
                }
                $condition = RelationshipCondition::fromArray($condition, ($path === '' ? '' : $path . '.') . 'condition');
            }
        }
        return new self(object: $object, relation: $relation, user: $user, condition: $condition);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['object' => $this->object, 'relation' => $this->relation, 'user' => $this->user, 'condition' => $this->condition?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
