<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

enum TupleOperation: string
{
    case TUPLE_OPERATION_WRITE = 'TUPLE_OPERATION_WRITE';
    case TUPLE_OPERATION_DELETE = 'TUPLE_OPERATION_DELETE';
}
