<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class Tuple implements \JsonSerializable
{
    public function __construct(
        public TupleKey $key,
        public \DateTimeImmutable $timestamp
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('key', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'key'));
        }
        if (!is_array($data['key'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'key'));
        }
        $key = TupleKey::fromArray($data['key'], ($path === '' ? '' : $path . '.') . 'key');
        if (!array_key_exists('timestamp', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'timestamp'));
        }
        if (!is_string($data['timestamp'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected date-time string', ($path === '' ? '' : $path . '.') . 'timestamp'));
        }
        $timestamp = new \DateTimeImmutable($data['timestamp']);
        return new self(key: $key, timestamp: $timestamp);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['key' => $this->key->toArray(), 'timestamp' => $this->timestamp->format(\DateTimeInterface::ATOM)], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
