<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class TypeDefinition implements \JsonSerializable
{
    public function __construct(
        public string $type,
        public ?Metadata $metadata = null,
        /** @var array<string, mixed>|null */
        public ?array $relations = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('type', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'type'));
        }
        if (!is_string($data['type'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'type'));
        }
        $type = $data['type'];
        $metadata = null;
        if (array_key_exists('metadata', $data)) {
            $metadata = $data['metadata'];
            if (!is_array($metadata)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'metadata'));
            }
            $metadata = Metadata::fromArray($metadata, ($path === '' ? '' : $path . '.') . 'metadata');
        }
        $relations = null;
        if (array_key_exists('relations', $data)) {
            $relations = $data['relations'];
            if (!is_array($relations)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'relations'));
            }
        }
        return new self(type: $type, metadata: $metadata, relations: $relations);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['type' => $this->type, 'metadata' => $this->metadata?->toArray(), 'relations' => $this->relations], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
