<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

enum TypeName: string
{
    case TYPE_NAME_UNSPECIFIED = 'TYPE_NAME_UNSPECIFIED';
    case TYPE_NAME_ANY = 'TYPE_NAME_ANY';
    case TYPE_NAME_BOOL = 'TYPE_NAME_BOOL';
    case TYPE_NAME_STRING = 'TYPE_NAME_STRING';
    case TYPE_NAME_INT = 'TYPE_NAME_INT';
    case TYPE_NAME_UINT = 'TYPE_NAME_UINT';
    case TYPE_NAME_DOUBLE = 'TYPE_NAME_DOUBLE';
    case TYPE_NAME_DURATION = 'TYPE_NAME_DURATION';
    case TYPE_NAME_TIMESTAMP = 'TYPE_NAME_TIMESTAMP';
    case TYPE_NAME_MAP = 'TYPE_NAME_MAP';
    case TYPE_NAME_LIST = 'TYPE_NAME_LIST';
    case TYPE_NAME_IPADDRESS = 'TYPE_NAME_IPADDRESS';
}
