<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

enum UnprocessableContentErrorCode: string
{
    case NO_THROTTLED_ERROR_CODE = 'no_throttled_error_code';
    case THROTTLED_TIMEOUT_ERROR = 'throttled_timeout_error';
}
