<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class Usersets implements \JsonSerializable
{
    public function __construct(
        /** @var list<Userset> */
        public array $child
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('child', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'child'));
        }
        if (!is_array($data['child'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'child'));
        }
        $childList = [];
        foreach ($data['child'] as $idx => $item) {
            if (!is_array($item)) {
                throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
            }
            $childList[] = Userset::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
        }
        $child = $childList;
        return new self(child: $child);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['child' => array_map(static fn(Userset $v): array => $v->toArray(), $this->child)], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
