<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class UsersetTreeDifference implements \JsonSerializable
{
    public function __construct(
        public Node $base,
        public Node $subtract
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('base', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'base'));
        }
        if (!is_array($data['base'])) {
            throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'base'));
        }
        $base = Node::fromArray($data['base'], ($path === '' ? '' : $path . '.') . 'base');
        if (!array_key_exists('subtract', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'subtract'));
        }
        if (!is_array($data['subtract'])) {
            throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'subtract'));
        }
        $subtract = Node::fromArray($data['subtract'], ($path === '' ? '' : $path . '.') . 'subtract');
        return new self(base: $base, subtract: $subtract);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['base' => $this->base->toArray(), 'subtract' => $this->subtract->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
