<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class UserTypeFilter implements \JsonSerializable
{
    public function __construct(
        public string $type,
        public ?string $relation = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('type', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'type'));
        }
        if (!is_string($data['type'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'type'));
        }
        $type = $data['type'];
        $relation = null;
        if (array_key_exists('relation', $data)) {
            $relation = $data['relation'];
            if ($relation === null) {
                $relation = null;
            } else {
                if (!is_string($relation)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'relation'));
                }
            }
        }
        return new self(type: $type, relation: $relation);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['type' => $this->type, 'relation' => $this->relation], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
