<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class User implements \JsonSerializable
{
    public function __construct(
        public ?FgaObject $object = null,
        public ?UsersetUser $userset = null,
        public ?TypedWildcard $wildcard = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $object = null;
        if (array_key_exists('object', $data)) {
            $object = $data['object'];
            if ($object === null) {
                $object = null;
            } else {
                if (!is_array($object)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'object'));
                }
                $object = FgaObject::fromArray($object, ($path === '' ? '' : $path . '.') . 'object');
            }
        }
        $userset = null;
        if (array_key_exists('userset', $data)) {
            $userset = $data['userset'];
            if ($userset === null) {
                $userset = null;
            } else {
                if (!is_array($userset)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'userset'));
                }
                $userset = UsersetUser::fromArray($userset, ($path === '' ? '' : $path . '.') . 'userset');
            }
        }
        $wildcard = null;
        if (array_key_exists('wildcard', $data)) {
            $wildcard = $data['wildcard'];
            if ($wildcard === null) {
                $wildcard = null;
            } else {
                if (!is_array($wildcard)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'wildcard'));
                }
                $wildcard = TypedWildcard::fromArray($wildcard, ($path === '' ? '' : $path . '.') . 'wildcard');
            }
        }
        return new self(object: $object, userset: $userset, wildcard: $wildcard);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['object' => $this->object?->toArray(), 'userset' => $this->userset?->toArray(), 'wildcard' => $this->wildcard?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
