<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class UsersetTreeTupleToUserset implements \JsonSerializable
{
    public function __construct(
        /** @var list<Computed> */
        public array $computed,
        public string $tupleset
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('computed', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'computed'));
        }
        if (!is_array($data['computed'])) {
            throw new FgaValidationException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'computed'));
        }
        $computedList = [];
        foreach ($data['computed'] as $idx => $item) {
            if (!is_array($item)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
            }
            $computedList[] = Computed::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
        }
        $computed = $computedList;
        if (!array_key_exists('tupleset', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'tupleset'));
        }
        if (!is_string($data['tupleset'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'tupleset'));
        }
        $tupleset = $data['tupleset'];
        return new self(computed: $computed, tupleset: $tupleset);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['computed' => array_map(static fn(Computed $v): array => $v->toArray(), $this->computed), 'tupleset' => $this->tupleset], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
