<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class UsersetTree implements \JsonSerializable
{
    public function __construct(
        public ?Node $root = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $root = null;
        if (array_key_exists('root', $data)) {
            $root = $data['root'];
            if (!is_array($root)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'root'));
            }
            $root = Node::fromArray($root, ($path === '' ? '' : $path . '.') . 'root');
        }
        return new self(root: $root);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['root' => $this->root?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
