<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class Users implements \JsonSerializable
{
    public function __construct(
        /** @var list<mixed> */
        public array $users
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('users', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'users'));
        }
        if (!is_array($data['users'])) {
            throw new FgaValidationException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'users'));
        }
        $usersList = [];
        foreach ($data['users'] as $idx => $item) {
            if (!is_string($item)) {
                throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . $idx));
            }
            $usersList[] = $item;
        }
        $users = $usersList;
        return new self(users: $users);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['users' => $this->users], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
