<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class Userset implements \JsonSerializable
{
    public function __construct(
        public ?ObjectRelation $computedUserset = null,
        public ?Difference $difference = null,
        public ?Usersets $intersection = null,
        /** @var array<string, mixed>|null */
        public ?array $thisUserset = null,
        public ?TupleToUserset $tupleToUserset = null,
        public ?Usersets $union = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $computedUserset = null;
        if (array_key_exists('computedUserset', $data)) {
            $computedUserset = $data['computedUserset'];
            if ($computedUserset === null) {
                $computedUserset = null;
            } else {
                if (!is_array($computedUserset)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'computedUserset'));
                }
                $computedUserset = ObjectRelation::fromArray($computedUserset, ($path === '' ? '' : $path . '.') . 'computedUserset');
            }
        }
        $difference = null;
        if (array_key_exists('difference', $data)) {
            $difference = $data['difference'];
            if ($difference === null) {
                $difference = null;
            } else {
                if (!is_array($difference)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'difference'));
                }
                $difference = Difference::fromArray($difference, ($path === '' ? '' : $path . '.') . 'difference');
            }
        }
        $intersection = null;
        if (array_key_exists('intersection', $data)) {
            $intersection = $data['intersection'];
            if ($intersection === null) {
                $intersection = null;
            } else {
                if (!is_array($intersection)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'intersection'));
                }
                $intersection = Usersets::fromArray($intersection, ($path === '' ? '' : $path . '.') . 'intersection');
            }
        }
        $thisUserset = null;
        if (array_key_exists('this', $data)) {
            $thisUserset = $data['this'];
            if ($thisUserset === null) {
                $thisUserset = null;
            } else {
                if (!is_array($thisUserset)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'this'));
                }
            }
        }
        $tupleToUserset = null;
        if (array_key_exists('tupleToUserset', $data)) {
            $tupleToUserset = $data['tupleToUserset'];
            if ($tupleToUserset === null) {
                $tupleToUserset = null;
            } else {
                if (!is_array($tupleToUserset)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'tupleToUserset'));
                }
                $tupleToUserset = TupleToUserset::fromArray($tupleToUserset, ($path === '' ? '' : $path . '.') . 'tupleToUserset');
            }
        }
        $union = null;
        if (array_key_exists('union', $data)) {
            $union = $data['union'];
            if ($union === null) {
                $union = null;
            } else {
                if (!is_array($union)) {
                    throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'union'));
                }
                $union = Usersets::fromArray($union, ($path === '' ? '' : $path . '.') . 'union');
            }
        }
        return new self(computedUserset: $computedUserset, difference: $difference, intersection: $intersection, thisUserset: $thisUserset, tupleToUserset: $tupleToUserset, union: $union);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['computedUserset' => $this->computedUserset?->toArray(), 'difference' => $this->difference?->toArray(), 'intersection' => $this->intersection?->toArray(), 'this' => $this->thisUserset, 'tupleToUserset' => $this->tupleToUserset?->toArray(), 'union' => $this->union?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
