<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class WriteRequestDeletes implements \JsonSerializable
{
    public function __construct(
        /** @var list<TupleKeyWithoutCondition> */
        public array $tupleKeys,
        public ?string $onMissing = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('tuple_keys', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'tuple_keys'));
        }
        if (!is_array($data['tuple_keys'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'tuple_keys'));
        }
        $tupleKeysList = [];
        foreach ($data['tuple_keys'] as $idx => $item) {
            if (!is_array($item)) {
                throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
            }
            $tupleKeysList[] = TupleKeyWithoutCondition::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
        }
        $tupleKeys = $tupleKeysList;
        $onMissing = null;
        if (array_key_exists('on_missing', $data)) {
            $onMissing = $data['on_missing'];
            if ($onMissing === null) {
                $onMissing = null;
            } else {
                if (!is_string($onMissing)) {
                    throw new FgaResponseDecodeException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'on_missing'));
                }
                if (!in_array($onMissing, [
                    0 => 'error',
                    1 => 'ignore',
                ], true)) {
                    throw new FgaResponseDecodeException(sprintf('%s: invalid enum value', ($path === '' ? '' : $path . '.') . 'on_missing'));
                }
            }
        }
        return new self(tupleKeys: $tupleKeys, onMissing: $onMissing);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['tuple_keys' => array_map(static fn(TupleKeyWithoutCondition $v): array => $v->toArray(), $this->tupleKeys), 'on_missing' => $this->onMissing], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
