<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaResponseDecodeException;

final readonly class WriteAssertionsBody implements \JsonSerializable
{
    public function __construct(
        /** @var list<Assertion> */
        public array $assertions
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('assertions', $data)) {
            throw new FgaResponseDecodeException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'assertions'));
        }
        if (!is_array($data['assertions'])) {
            throw new FgaResponseDecodeException(sprintf('%s: expected array', ($path === '' ? '' : $path . '.') . 'assertions'));
        }
        $assertionsList = [];
        foreach ($data['assertions'] as $idx => $item) {
            if (!is_array($item)) {
                throw new FgaResponseDecodeException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . $idx));
            }
            $assertionsList[] = Assertion::fromArray($item, ($path === '' ? '' : $path . '.') . (string) $idx);
        }
        $assertions = $assertionsList;
        return new self(assertions: $assertions);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['assertions' => array_map(static fn(Assertion $v): array => $v->toArray(), $this->assertions)], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
