<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class WriteBody implements \JsonSerializable
{
    public function __construct(
        public ?string $authorizationModelId = null,
        public ?WriteRequestDeletes $deletes = null,
        public ?WriteRequestWrites $writes = null
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        $authorizationModelId = null;
        if (array_key_exists('authorization_model_id', $data)) {
            $authorizationModelId = $data['authorization_model_id'];
            if (!is_string($authorizationModelId)) {
                throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'authorization_model_id'));
            }
        }
        $deletes = null;
        if (array_key_exists('deletes', $data)) {
            $deletes = $data['deletes'];
            if (!is_array($deletes)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'deletes'));
            }
            $deletes = WriteRequestDeletes::fromArray($deletes, ($path === '' ? '' : $path . '.') . 'deletes');
        }
        $writes = null;
        if (array_key_exists('writes', $data)) {
            $writes = $data['writes'];
            if (!is_array($writes)) {
                throw new FgaValidationException(sprintf('%s: expected object', ($path === '' ? '' : $path . '.') . 'writes'));
            }
            $writes = WriteRequestWrites::fromArray($writes, ($path === '' ? '' : $path . '.') . 'writes');
        }
        return new self(authorizationModelId: $authorizationModelId, deletes: $deletes, writes: $writes);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['authorization_model_id' => $this->authorizationModelId, 'deletes' => $this->deletes?->toArray(), 'writes' => $this->writes?->toArray()], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
