<?php

// Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@c0650ce2169bcb39a72d73841fb531c200e32248
declare(strict_types=1);

namespace Curentis\OpenFga\Model;

use Curentis\OpenFga\Exception\FgaValidationException;

final readonly class WriteAuthorizationModelResponse implements \JsonSerializable
{
    public function __construct(
        public string $authorizationModelId
    ) {}

    /** @param array<array-key, mixed> $data */
    public static function fromArray(array $data, string $path = ''): self
    {
        if (!array_key_exists('authorization_model_id', $data)) {
            throw new FgaValidationException(sprintf('%s: required', ($path === '' ? '' : $path . '.') . 'authorization_model_id'));
        }
        if (!is_string($data['authorization_model_id'])) {
            throw new FgaValidationException(sprintf('%s: expected string', ($path === '' ? '' : $path . '.') . 'authorization_model_id'));
        }
        $authorizationModelId = $data['authorization_model_id'];
        return new self(authorizationModelId: $authorizationModelId);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return array_filter(['authorization_model_id' => $this->authorizationModelId], static fn(mixed $v): bool => $v !== null);
    }

    /** @return array<string, mixed> */
    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
