<?php

declare(strict_types=1);

/**
 * Allow-list of OpenAPI schema names generated into src/Model (core FGA API, excludes AuthZEN).
 *
 * @return list<string>
 */
return  [
    0 => 'AbortedMessageResponse',
    1 => 'Any',
    2 => 'Assertion',
    3 => 'AssertionTupleKey',
    4 => 'AuthErrorCode',
    5 => 'AuthorizationModel',
    6 => 'BatchCheckBody',
    7 => 'BatchCheckItem',
    8 => 'BatchCheckResponse',
    9 => 'BatchCheckSingleResult',
    10 => 'CheckBody',
    11 => 'CheckError',
    12 => 'CheckRequestTupleKey',
    13 => 'CheckResponse',
    14 => 'Computed',
    15 => 'Condition',
    16 => 'ConditionMetadata',
    17 => 'ConditionParamTypeRef',
    18 => 'ConsistencyPreference',
    19 => 'ContextualTupleKeys',
    20 => 'CreateStoreRequest',
    21 => 'CreateStoreResponse',
    22 => 'DirectUserset',
    23 => 'ErrorCode',
    24 => 'ExpandBody',
    25 => 'ExpandRequestTupleKey',
    26 => 'ExpandResponse',
    27 => 'ForbiddenResponse',
    28 => 'GetStoreResponse',
    29 => 'InternalErrorCode',
    30 => 'InternalErrorMessageResponse',
    31 => 'Leaf',
    32 => 'ListObjectsBody',
    33 => 'ListObjectsResponse',
    34 => 'ListStoresResponse',
    35 => 'ListUsersBody',
    36 => 'ListUsersResponse',
    37 => 'Metadata',
    38 => 'Node',
    39 => 'Nodes',
    40 => 'NotFoundErrorCode',
    41 => 'Object',
    42 => 'ObjectRelation',
    43 => 'PathUnknownErrorMessageResponse',
    44 => 'ReadAssertionsResponse',
    45 => 'ReadAuthorizationModelResponse',
    46 => 'ReadAuthorizationModelsResponse',
    47 => 'ReadBody',
    48 => 'ReadChangesResponse',
    49 => 'ReadRequestTupleKey',
    50 => 'ReadResponse',
    51 => 'RelationMetadata',
    52 => 'RelationReference',
    53 => 'RelationshipCondition',
    54 => 'SourceInfo',
    55 => 'Status',
    56 => 'Store',
    57 => 'StreamedListObjectsBody',
    58 => 'StreamedListObjectsResponse',
    59 => 'Tuple',
    60 => 'TupleChange',
    61 => 'TupleKey',
    62 => 'TupleKeyWithoutCondition',
    63 => 'TupleOperation',
    64 => 'TypeDefinition',
    65 => 'TypeName',
    66 => 'TypedWildcard',
    67 => 'UnauthenticatedResponse',
    68 => 'UnprocessableContentErrorCode',
    69 => 'UnprocessableContentMessageResponse',
    70 => 'User',
    71 => 'UserTypeFilter',
    72 => 'Users',
    73 => 'Userset',
    74 => 'UsersetTree',
    75 => 'UsersetTree.Difference',
    76 => 'UsersetTree.TupleToUserset',
    77 => 'UsersetUser',
    78 => 'Usersets',
    79 => 'ValidationErrorMessageResponse',
    80 => 'Wildcard',
    81 => 'WriteAssertionsBody',
    82 => 'WriteAuthorizationModelBody',
    83 => 'WriteAuthorizationModelResponse',
    84 => 'WriteBody',
    85 => 'WriteRequestDeletes',
    86 => 'WriteRequestWrites',
    87 => 'WriteResponse',
    88 => 'v1.Difference',
    89 => 'v1.TupleToUserset',
];
