<?php

declare(strict_types=1);

namespace Curentis\OpenFga\Tools\Codegen\Generator;

final class EnumRenderer
{
    public function __construct(
        private readonly string $sourceSha,
    ) {}

    /**
     * @param array<string, mixed> $schema
     */
    public function render(string $schemaName, array $schema): string
    {
        $className = NameConverter::schemaToClassName($schemaName);
        $values = $schema['enum'] ?? [];
        if (!is_array($values)) {
            $values = [];
        }
        $cases = [];
        foreach ($values as $value) {
            if (!is_string($value) && !is_int($value)) {
                continue;
            }
            $caseName = $this->enumCaseName((string) $value);
            $cases[] = sprintf("    case %s = '%s';", $caseName, addslashes((string) $value));
        }

        $header = $this->fileHeader();

        return <<<PHP
            {$header}
            namespace Curentis\\OpenFga\\Model;

            enum {$className}: string
            {
            {$this->indent(implode("\n", $cases), 0)}
            }

            PHP;
    }

    private function enumCaseName(string $value): string
    {
        if ($value === '') {
            return 'EMPTY';
        }

        return strtoupper(preg_replace('/[^A-Za-z0-9_]/', '_', $value) ?? $value);
    }

    private function fileHeader(): string
    {
        return <<<PHP
            <?php

            // Code generated by tools/codegen. DO NOT EDIT. Source: openfga/api@{$this->sourceSha}
            declare(strict_types=1);


            PHP;
    }

    private function indent(string $body, int $level): string
    {
        if ($body === '') {
            return '';
        }

        $pad = str_repeat('    ', $level);

        return $pad . str_replace("\n", "\n" . $pad, $body);
    }
}
